# Generated by Django 4.2.5 on 2023-11-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(blank=True, null=True, upload_to="item_images/"),
                ),
            ],
        ),
    ]
