# Generated by Django 4.2.4 on 2023-11-20 04:41

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[cart.models.validate_discount_code]),
        ),
    ]
