# Generated by Django 4.2.5 on 2023-11-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item", name="quantity", field=models.IntegerField(default=1),
        ),
    ]
