# Generated by Django 4.2.5 on 2023-11-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="user", new_name="customer",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_price",
            new_name="order_size_in_dollars",
        ),
        migrations.AlterField(
            model_name="order", name="order_date", field=models.DateTimeField(),
        ),
    ]
